name = "JLBoostMLJ"
uuid = "8b86df2c-1bc3-481d-95df-1c4d5a20ed95"
authors = ["Dai ZJ <zhuojia.dai@gmail.com>"]
version = "0.1.9"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JLBoost = "13d6d4a1-5e7f-472c-9ebc-8123a4fbb95f"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"

[compat]
DataFrames = "0.21, 0.22"
JLBoost = "^0.1.8"
LossFunctions = "0.5, 0.6"
MLJ = "0.10, 0.11, 0.12, 0.13, 0.14"
MLJBase = "0.12, 0.13, 0.14, 0.15"
ScientificTypes = "0.7, 0.8, 1.0"
julia = "1"

[extras]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test"]
